apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: searchpes.project.openubl
spec:
  group: project.openubl
  scope: Namespaced
  names:
    plural: searchpes
    singular: searchpe
    kind: Searchpe
    shortNames:
      - sp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                html:
                  type: string
