apiVersion: v1
kind: Namespace
metadata:
  name: searchpe-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: searchpe-operator
  namespace: searchpe-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchpe-operator
  namespace: searchpe-operator
spec:
  selector:
    matchLabels:
      app: searchpe-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: searchpe-operator
    spec:
      serviceAccount: searchpe-operator
      containers:
        - name: operator
          image: projectopenubl/searchpe-operator
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
  - kind: ServiceAccount
    name: searchpe-operator
    namespace: searchpe-operator
roleRef:
  kind: ClusterRole
  name: searchpe-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: searchpe-operator
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - project.openubl
    resources:
      - searchpes
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
      - configmaps
    verbs:
      - '*'
