apiVersion: project.openubl/v1
kind: Searchpe
metadata:
  name: hellows
spec:
  html: |
    <html>
      <head>
        <title>Hello Operator World</title>
      </head>
      <body>
        Hello Operator World v1!
      </body>
    </html>
